# pub static PASTEL_RED: Color = Color::new(0xff6961);
# const PROGRESSBAR_EMPTY_CHAR: char = '░';
# const PROGRESSBAR_FULL_CHAR: char = '█';

services:
  database:
    image: "postgres:15.3"
    restart: "unless-stopped"
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432/tcp"
